Repository cms-sw/cmssw-config, pull requests merged in 2024-03, with the labels that each got.

#104 Copy all CFIPYTHON_PACKAGE_FILES files to cfipython store
  SCRAM/GMake/Makefile.rules
  SCRAM/Plugins/CMSSW/ExtraBuildRule.py
Labels: orp-pending, pending-signatures, externals-pending, tests-started, requires-external

#107 Fix rocm compilation of dev.cc files
  SCRAM/GMake/Makefile.rocm
Labels: orp-pending, pending-signatures, tests-approved, externals-pending

#106 fix alpaka/rocm rules; use hipcc linker for rocm
  SCRAM/Plugins/BuildRules.py
Labels: orp-pending, pending-signatures, externals-pending, tests-started
